const jiife = require('jiife');
const xl = 'node_modules/xtal-latx/';
const tr = 'node_modules/trans-render/';
const xe = 'node_modules/xtal-element/';
const xlDep = [xl + 'define.js', xl + 'xtal-latx.js'];
const trDep = [tr + 'init.js', tr + 'update.js', tr + 'repeatInit.js', tr + 'repeatUpdate.js', tr + 'interpolate.js'];
const xeDep = [xe + 'xtal-element.js'];
const common = xlDep.concat(trDep).concat(xeDep);
jiife.processFiles(common.concat(['wc-info-base.js']), 'dist/wc-info-base.iife.js');
jiife.processFiles(common.concat(['wc-info-base.js', 'wc-info.js']), 'dist/wc-info.iife.js');